package com.example.OpenAPISpec;

import com.example.OpenAPISpec.entity.Student;
import com.example.OpenAPISpec.repository.StudentRepository;
import io.swagger.v3.oas.annotations.OpenAPIDefinition;
import io.swagger.v3.oas.annotations.info.Info;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import java.util.ArrayList;
import java.util.List;

@SpringBootApplication
@OpenAPIDefinition(info = @Info(title = "Student API", version = "1.0", description = "API for managing students"))
public class OpenApiSpecApplication {
	public static void main(String[] args) {
		SpringApplication.run(OpenApiSpecApplication.class, args);
	}

	@Bean
	public CommandLineRunner init(StudentRepository repo) {
		return args -> {
			List<Student> s=new ArrayList<>();
			//As id will be autogenerated we have to pass it as null below
			s.add(new Student(null, "Name1", "adrs1", "cls1",1234567898,1l));
			s.add(new Student(null, "Name2", "adrs2", "cls2",1273849342,2l));
			s.add(new Student(null, "Name3", "adrs3", "cls3",1736482935,3l));
	repo.saveAll(s);
		};
	}
}
